# Generated by Django 5.2.7 on 2025-10-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='patient',
        ),
        migrations.DeleteModel(
            name='BloodStock',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='request_status',
        ),
        migrations.DeleteModel(
            name='BloodRequest',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
