# Generated by Django 5.2.7 on 2025-10-08 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodmanager', '0005_bloodstock_hospital_alter_bloodstock_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodstock',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bloodmanager.hospital'),
        ),
    ]
