# Generated by Django 5.2.7 on 2025-10-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodmanager', '0006_alter_bloodstock_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='address',
        ),
        migrations.AddField(
            model_name='hospital',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
