# Generated by Django 5.2.7 on 2025-10-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodmanager', '0007_remove_hospital_address_hospital_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
