# Generated by Django 5.2.7 on 2025-10-09 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodmanager', '0008_patient_approved_alter_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('hemoglobin_level', models.FloatField()),
                ('has_disease', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodmanager.donor')),
            ],
        ),
    ]
