# Generated by Django 5.2.7 on 2025-10-11 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodmanager', '0012_bloodrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodRequest',
        ),
    ]
