# Generated by Django 5.2.7 on 2025-10-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodmanager', '0013_delete_bloodrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='donor_photos/'),
        ),
    ]
