# Generated by Django 5.2.7 on 2025-10-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodmanager', '0014_donor_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorhealthcheck',
            name='recent_medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorhealthcheck',
            name='recent_surgeries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorhealthcheck',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorhealthcheck',
            name='tattoos_or_piercings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorhealthcheck',
            name='travel_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
