# Generated by Django 5.2.7 on 2025-10-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodmanager', '0016_donationslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationslot',
            name='created_at',
        ),
        migrations.AddField(
            model_name='donationslot',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donationslot',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
